POST http://localhost:3001/user/register
Content-Type: application/json

{
  "username": "anag",
  "password": "123456",
  "img":"https://imgs.search.brave.com/rwE-hC6ESt3hBJZhImPkb-KvU26bLDKVe-OKv1y50-M/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzE0LzQz/LzU1LzE0NDM1NWQ3/YjM2YzVmNjQ2NDM1/NDIzNzk4MjgxY2U5/LmpwZw"
}


######

POST http://localhost:3001/user/login
Content-Type: application/json

{
  "username": "juanp",
  "password": "123456"
}


#####
GET http://localhost:3001/user/search?search=j
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFhMDQzZWU0LTkyZDMtNGM1NC05YzBkLTI0NDdhMDRjYTIyZiIsInVzZXJuYW1lIjoiam9obl9kb2UiLCJpbWciOm51bGwsImlhdCI6MTc0NDgzNzIyOSwiZXhwIjoxNzQ0ODQ0NDI5fQ.Z1lEBv5z_Lq6J64HGnnmEJZ5QbQ7F53XozF-S_je_lM


######

GET http://localhost:3001/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2YjNlMjFhLTVmMGYtNGUxOS1iMmQ2LTdhNGM5NWExZmQwMSIsInVzZXJuYW1lIjoianVhbnAiLCJpbWciOiJodHRwczovL2V4YW1wbGUuY29tL2ltYWdlcy9qdWFucC5qcGciLCJpYXQiOjE3NDY2NDI3NDIsImV4cCI6MTc0NjY0OTk0Mn0.goktnP_8s_SrpPNusw5B5V2pOiSXEZu5LXmD8CsOD5Y


####
POST http://localhost:3001/chat/create/juanp
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRmOWUzYjhhLTYxYTYtNDJjNS1hNTg4LWYyNWE4MGRlNTcwZiIsInVzZXJuYW1lIjoiYW5hZyIsImltZyI6Imh0dHBzOi8vaW1ncy5zZWFyY2guYnJhdmUuY29tL3J3RS1oQzZFU3QzaEJKWmhJbVBrYi1LdlUyNmJMREtWZS1PS3YxeTUwLU0vcnM6Zml0Ojg2MDowOjA6MC9nOmNlL2FIUjBjSE02THk5cExuQnAvYm1sdFp5NWpiMjB2YjNKcC9aMmx1WVd4ekx6RTBMelF6L0x6VTFMekUwTkRNMU5XUTMvWWpNMll6Vm1OalEyTkRNMS9OREl6TnprNE1qZ3hZMlU1L0xtcHdadyIsImlhdCI6MTc0NjY1MDg2NSwiZXhwIjoxNzQ2NjU4MDY1fQ.Ew2XPHD11LH7UQ_R2W15HnZ1o63AJLanJnF6zOvH_sQ

#####

GET http://localhost:3001/chat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2YjNlMjFhLTVmMGYtNGUxOS1iMmQ2LTdhNGM5NWExZmQwMSIsInVzZXJuYW1lIjoianVhbnAiLCJpbWciOiJodHRwczovL2V4YW1wbGUuY29tL2ltYWdlcy9qdWFucC5qcGciLCJpYXQiOjE3NDY2NDI3NDIsImV4cCI6MTc0NjY0OTk0Mn0.goktnP_8s_SrpPNusw5B5V2pOiSXEZu5LXmD8CsOD5Y


#####

POST http://localhost:3001/chat/message/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2YjNlMjFhLTVmMGYtNGUxOS1iMmQ2LTdhNGM5NWExZmQwMSIsInVzZXJuYW1lIjoianVhbnAiLCJpbWciOiJodHRwczovL2V4YW1wbGUuY29tL2ltYWdlcy9qdWFucC5qcGciLCJpYXQiOjE3NDY5MDY4NzAsImV4cCI6MTc0NjkxNDA3MH0.0AMfZCpyHpxx-tgaOkZ2Ipz1fzm9_CZytakErk3N3g4
Content-Type: application/json

{
  "description": "hola",
  "mine": true,
  "date":"2025-04-16 18:18:00"
}

####

GET http://localhost:3001/chat/message/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2YjNlMjFhLTVmMGYtNGUxOS1iMmQ2LTdhNGM5NWExZmQwMSIsInVzZXJuYW1lIjoianVhbnAiLCJpbWciOiJodHRwczovL2V4YW1wbGUuY29tL2ltYWdlcy9qdWFucC5qcGciLCJpYXQiOjE3NDY5MDY4NzAsImV4cCI6MTc0NjkxNDA3MH0.0AMfZCpyHpxx-tgaOkZ2Ipz1fzm9_CZytakErk3N3g4
