POST http://localhost:3001/user/register
Content-Type: application/json

{
  "username": "anag",
  "password": "123456",
  "img":"https://imgs.search.brave.com/rwE-hC6ESt3hBJZhImPkb-KvU26bLDKVe-OKv1y50-M/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzE0LzQz/LzU1LzE0NDM1NWQ3/YjM2YzVmNjQ2NDM1/NDIzNzk4MjgxY2U5/LmpwZw"
}


######

POST http://localhost:3001/user/login
Content-Type: application/json

{
  "username": "juanp",
  "password": "123456"
}


#####
GET http://localhost:3001/user/search?search=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2YjNlMjFhLTVmMGYtNGUxOS1iMmQ2LTdhNGM5NWExZmQwMSIsInVzZXJuYW1lIjoianVhbnAiLCJpbWciOiJodHRwczovL2V4YW1wbGUuY29tL2ltYWdlcy9qdWFucC5qcGciLCJpYXQiOjE3NDcwODM3OTcsImV4cCI6MTc0NzA5MDk5N30.P0DsKwSrMW2dJVyT6OS_ahgv5Q1u6uCv1JMJ1xUAtEg


######

GET http://localhost:3001/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2YjNlMjFhLTVmMGYtNGUxOS1iMmQ2LTdhNGM5NWExZmQwMSIsInVzZXJuYW1lIjoianVhbnAiLCJpbWciOiJodHRwczovL2V4YW1wbGUuY29tL2ltYWdlcy9qdWFucC5qcGciLCJpYXQiOjE3NDY2NDI3NDIsImV4cCI6MTc0NjY0OTk0Mn0.goktnP_8s_SrpPNusw5B5V2pOiSXEZu5LXmD8CsOD5Y


####
POST http://localhost:3001/chat/create/santiago
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2YjNlMjFhLTVmMGYtNGUxOS1iMmQ2LTdhNGM5NWExZmQwMSIsInVzZXJuYW1lIjoianVhbnAiLCJpbWciOiJodHRwczovL2V4YW1wbGUuY29tL2ltYWdlcy9qdWFucC5qcGciLCJpYXQiOjE3NDcwOTcyNjMsImV4cCI6MTc0NzEwNDQ2M30.a8QeMyNTTxEKFpv1gqLtbZ_MoMK9Ihg6SJc9FM3w0MU

#####

GET http://localhost:3001/chat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2YjNlMjFhLTVmMGYtNGUxOS1iMmQ2LTdhNGM5NWExZmQwMSIsInVzZXJuYW1lIjoianVhbnAiLCJpbWciOiJodHRwczovL2V4YW1wbGUuY29tL2ltYWdlcy9qdWFucC5qcGciLCJpYXQiOjE3NDY2NDI3NDIsImV4cCI6MTc0NjY0OTk0Mn0.goktnP_8s_SrpPNusw5B5V2pOiSXEZu5LXmD8CsOD5Y



####

GET http://localhost:3001/chat/message/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2YjNlMjFhLTVmMGYtNGUxOS1iMmQ2LTdhNGM5NWExZmQwMSIsInVzZXJuYW1lIjoianVhbnAiLCJpbWciOiJodHRwczovL2V4YW1wbGUuY29tL2ltYWdlcy9qdWFucC5qcGciLCJpYXQiOjE3NDY5MDY4NzAsImV4cCI6MTc0NjkxNDA3MH0.0AMfZCpyHpxx-tgaOkZ2Ipz1fzm9_CZytakErk3N3g4
